## Import Necesary Libraries

In [5]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
# https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

In [14]:
# GaussianNB     : Structured Data 
# MultinomialNB  : Text Classification

In [6]:
data = pd.read_csv("./data/diabetes.csv")

In [7]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
# will you cover prior and posterior probability

In [11]:
# P(Outcome/'Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome')

In [8]:
data.shape

(768, 9)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [10]:
data.isnull().mean()

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

In [12]:
# Question : IS EDA required in Naive bayes required or not ?
# EDA is always required , or always to be done

In [11]:
# Split the data into features (X) and target (y) 
X = data.drop('Outcome', axis=1) # Features 
y = data['Outcome'] # Target (1 = diabetes, 0 = no diabetes)

In [12]:
# Split the dataset into training and test sets 
# any random_state can be given
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [13]:
print(X_train.shape)
print(X_test.shape)

(614, 8)
(154, 8)

In [14]:
# Intialize the Gaussian Naive Bayes Classifier
nb_model = GaussianNB()

In [15]:
# Train the model 
nb_model.fit(X_train,y_train)

GaussianNB()

In [16]:
#we used GaussianNB because we had numeric values in independent variables?

y_pred_train = nb_model.predict(X_train)
y_pred_test = nb_model.predict(X_test)

In [17]:
# Evaluate the Model's Performace
accuracy_train = accuracy_score(y_train,y_pred_train)
print(f"Accuracy: {accuracy_train: .2f}")

Accuracy:  0.75

In [18]:
#Evaluate the model's performance
accuracy_test = accuracy_score(y_test,y_pred_test)
print(f"Accuracy: {accuracy_test: .2f}")

Accuracy:  0.77

In [ ]:
# In GLM there was only Predict which was giving Probability, Naive Bayes has both predict and predict_proba

### **Text Classification**

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
# Sample dataset: text and labels (spam or ham) 
texts = [ 
    "Free money now!!!", 
    "Hey, are we still meeting tomorrow?", 
    "Congratulations! You've won a free gift card!", 
    "Reminder about your appointment next week", 
    "Urgent! Reply to claim your prize!", 
    "Let's catch up later tonight.", 
    "Exclusive offer for you!",
    "This is not a spam message.", 
] 
# Corresponding labels: 1 for spam, 0 for ham 
labels = [1, 0, 1, 0, 1, 0, 1, 0]

In [27]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts) # Converts text to feature vectors

In [40]:
cols  = vectorizer.get_feature_names_out()
cols

pd.set_option("display.max_columns",None)
pd.DataFrame(X.toarray(),columns = cols)

,about,appointment,are,card,catch,claim,congratulations,exclusive,for,free,gift,hey,is,later,let,meeting,message,money,next,not,now,offer,prize,reminder,reply,spam,still,this,to,tomorrow,tonight,up,urgent,ve,we,week,won,you,your
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0
3,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1
5,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0

In [33]:
print(X_train.toarray())

[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0
  0 0 0]
 [0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0
  0 0 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 1]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0]]

In [26]:
# Split the data 
X_train, X_test, y_train,y_test = train_test_split(X,labels, test_size=0.2,random_state=42)

In [25]:
# Initialize Multinomial Naive Bayes
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train,y_train)

MultinomialNB()

In [30]:
y_pred_train = nb_classifier.predict(X_train)
y_pred_test = nb_classifier.predict(X_test)

In [31]:
# Evaluate the Model's Performace
accuracy_train = accuracy_score(y_train,y_pred_train)
print(f"Accuracy: {accuracy_train: .2f}")

Accuracy:  1.00

In [32]:
#Evaluate the model's performance
accuracy_test = accuracy_score(y_test,y_pred_test)
print(f"Accuracy: {accuracy_test: .2f}")

Accuracy:  1.00